#!/bin/zsh

# Sourced from ~/.zshrc before oh-my-zsh loads its plugins (see there).
# ~/.profile already puts the default node's bin on PATH, so lazy only defers
# the nvm function: nvm, node, npm, npx, pnpm, yarn and corepack load it on
# first use; other npm CLIs run straight from that bin.
zstyle ':omz:plugins:nvm' lazy yes
zstyle ':omz:plugins:nvm' autoload yes
zstyle ':omz:plugins:nvm' silent-autoload yes # optionally remove the output generated by NVM when autoloading
