Host *
    StrictHostKeyChecking accept-new

Host pku
    PubkeyAcceptedAlgorithms +ssh-rsa

Host sherlock
    RemoteCommand /bin/bash -c 'source /etc/profile 2>/dev/null && exec "$HOME/micromamba/envs/login/bin/zsh" -il'

Host marlowe
    RemoteCommand /bin/bash -c 'source /etc/profile 2>/dev/null && exec "$HOME/micromamba/envs/login/bin/zsh" -il'
