Host sherlock
    HostName login.sherlock.stanford.edu
    User zyli2002
    RequestTTY force
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials yes
    ControlMaster auto
    ControlPersist yes
    ControlPath ~/.ssh/%C

Host sherlock-plain
    HostName login.sherlock.stanford.edu
    User zyli2002
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials yes
    ControlMaster auto
    ControlPersist yes
    ControlPath ~/.ssh/%C

Host sherlock-dtn
    HostName dtn.sherlock.stanford.edu
    User zyli2002
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials yes
    ControlMaster auto
    ControlPersist yes
    ControlPath ~/.ssh/%C
    Ciphers aes128-gcm@openssh.com
    Compression no
    ServerAliveInterval 60
    IPQoS throughput

Host marlowe
    HostName login.marlowe.stanford.edu
    User zyli2002
    RequestTTY force
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials yes
    ControlMaster auto
    ControlPersist yes
    ControlPath ~/.ssh/%C

Host marlowe-plain
    HostName login.marlowe.stanford.edu
    User zyli2002
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials yes
    ControlMaster auto
    ControlPersist yes
    ControlPath ~/.ssh/%C
